development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: f14_bitz
  password: f14_bitz_gfhjkm
  database: f14_bitz
  schema_search_path: public
  encoding: utf8
  template: template1

test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: f14_bitz
  password: f14_bitz_gfhjkm
  database: f14_bitz
  schema_search_path: public
  encoding: utf8
  template: template1

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: f14_bitz
  password: f14_bitz_gfhjkm
  database: f14_bitz
#  database: f14_bitz
  schema_search_path: public
  encoding: utf8
  template: template1


