development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: vedmak2014_bitz
  password: vedmak2014_bitz_gfhjkm
  database: steam2016_bitz
  schema_search_path: public
  encoding: utf8
  template: template1

test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: vedmak2014_bitz
  password: vedmak2014_bitz_gfhjkm
  database: steam2016_bitz
  schema_search_path: public
  encoding: utf8
  template: template1

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: vedmak2014_bitz
  password: vedmak2014_bitz_gfhjkm
  database: steam2016_bitz
#  database: vedmak2014_bitz
  schema_search_path: public
  encoding: utf8
  template: template1


