development:
  adapter: postgresql
  host: localhost
  port: 5432
  username: melkor
  password: gfhjkm
  database: angband
  schema_search_path: public
  encoding: utf8
  template: template1

test:
  adapter: postgresql
  host: localhost
  port: 5432
  username: melkor
  password: gfhjkm
  database: angband_test
  schema_search_path: public
  encoding: utf8
  template: template1

production:
  adapter: postgresql
  host: localhost
  port: 5432
  username: melkor
  password: gfhjkm
  database: angband
  schema_search_path: public
  encoding: utf8
  template: template1


